### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by joaomoreira-obvio** [jnimmo/hass-intesisbox#49] opened 2023-08-08 12:40 UTC
Unable to prepare setup for platform intesisbox.climate: Platform not found (cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py))

Currently on Home Assistant OS 10.4
Core 2023.8.1

Can you please take a look?
Thank you very much

**Comment by Glirido** [comment] 2023-08-09 06:21
I think its a duplicate of #47

**Closed** 2024-03-10 08:53 UTC
